### ISSUE TITLE
Taskbar issues with newer versions

### ISSUE THREAD

**Issue by ottop** [bbidulock/icewm#559]
Having used IceWM across many Linux distributions with different versions in their repositories, there is an issue I have noticed with newer versions of IceWM. On the other hand, older versions do not have this issue as far as I have seen. 

The issue in question has to do with the system tray and the taskbar. I personally do not like the system tray and it forces the taskbar to be too thick for my liking. I thus prefer turning it off. However, the newer versions don't seem to like me doing this. 

Disabling the system tray breaks the task bar in such a manner that the workspace buttons do not appear and the taskbar is partially black until I move workspaces. 

Here's an image: [https://i.imgur.com/QWtWwgu.png](url)

As far as the versions go, for instance OpenSuse Leap's 1.4.2 and Debian's 1.4.3 work with no issues, but OpenSuse Tumbleweed, Arch Linux, Gentoo and Ubuntu have the issue and all of them have a newer IceWM version than the ones where it has worked.

I have also faced the issue on both, my desktop and laptop, so it is likely not due to my hardware.

**Comment by gijsbers** [comment]
Not reproducable sofar. Is this for 2.2.1?
Could you start from a clean preferences and test which
changes are minimally required to reproduce this?

**Comment by gijsbers** [comment]
Maybe this is similar to #542 and fixed now?

**Comment by ottop** [comment]
> Maybe this is similar to #542 and fixed now?

My preference file has never been in such a manner where I would have had showworkspaces off, but if it isn't reproduceable in 2.2.1 then it may be fixed by now. I'm going to test it out to see whether this is the case for me or not.

**Comment by ottop** [comment]
Having tested 2.2.1 on Manjaro (also on a different computer from either of the 2 that I have tested it with before), I have noticed that the issue is still present. Whenever I disable system tray from the stock preference file or a straight copy paste of my preferences file that works in 1.4.3, I get the issue. It definitely looks similar to the #542 issue, but the cause seems to be in disabling system tray.

**Comment by gijsbers** [comment]
With a preferences with only `TaskBarEnableSystemTray=0` it still doesn't reproduce, no matter what theme.

**Comment by ottop** [comment]
> With a preferences with only `TaskBarEnableSystemTray=0` it still doesn't reproduce, no matter what theme.

I definitely get the issue whenever I do the same. I wonder if it has to do with a newer version of some other package, though the issue seems to have been here for quite a while judging by Ubuntu having the issue on IceWM 1.6.6.

**Comment by gijsbers** [comment]
Found it! Tricky to find. Thanks for reporting!
